### ISSUE TITLE
Use of Client Hints for Chrome-facilitated testing

### ISSUE THREAD

**Issue by rowan-m** [GoogleChromeLabs/privacy-sandbox-dev-support#114]
Chrome is planning to use client hints to provide traffic labels for each of the testing modes. Do you have any concerns or feedback about using client hints for this purpose?

See https://developer.chrome.com/docs/privacy-sandbox/chrome-testing/ for context.

**Comment by dmdabbs** [comment]
Some background on your motivation for proposing UA-CH for the traffic labels would be helpful. 

Your proposed CH would be low entropy sent alongside the current defaults, yes? Servers should not be forced to opt in via `Accept-CH`. 

```
sec-ch-ua: "Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"

sec-ch-ua-sandbox-mode-a: ?1
```

Probably shouldn't be reflected in `NavigatorUAData` since a server wouldn't be able to detect the presence/absence of its third-party cookie until processing a request.

Client Hints are only sent on secure requests versus a garden variety header that would be available on all traffic.

**Comment by rowan-m** [comment]
> new APIs are restricted to secure environments

And just to complete the reference for anyone reading along, existing third-party cookies must already specify both `SameSite=None` and `Secure` so will not be present in insecure (e.g. non-HTTPS) contexts.

**Comment by lbdvt** [comment]
Would the labels be only accessible through [CH](https://developer.chrome.com/articles/user-agent-client-hints/)?

If so, I understand that an HTTP response has to be sent first with the proper Accept-CH header.

From a header bidding perspective, a bidder may not have had the opportunity to do so before its bidding endpoint is called for a bid request.

Indeed, the header bidding wrapper scripts may be hosted on the publishers' servers. In that case, Adding the Accept-CH header to an HTTP response and accessing the label in subsequent HTTP queries would require changes on the publishers' web server, correct? If so, it looks unlikely for this change to happen at scale. 

Would you consider adding the header to all HTTP requests (without the need for the previous HTTP response with Accept-CH header)?

**Comment by dmdabbs** [comment]
The announcement indicated it would be a "low-entropy client hint." They are [safe to send by default](https://wicg.github.io/client-hints-infrastructure/#low-entropy-table).

**Comment by dmdabbs** [comment]
@rowan-m the initial responses and engagement were encouraging. 
We inquired in the [recent WICG call](https://github.com/WICG/turtledove/blob/main/meetings/2023-06-21-FLEDGE-call-minutes.md), but understandibly that team can't speak to a cross-cutting concern like the testing proposal. 
A proposal and a forum in which to discuss it would be welcome.
It is approaching six weeks since you posted these three questions.

**Comment by rowan-m** [comment]
Appreciate the comments! We published https://developer.chrome.com/blog/privacy-sandbox-launch/#chrome-facilitated-testing-modes just recently and in there we're now on for providing an update on the testing modes in mid-August where I believe we will be able to provide more clarity on both the form and granularity of the labels.

**Comment by rowan-m** [comment]
Updating this issue with the implementation details available on https://developer.chrome.com/docs/privacy-sandbox/chrome-testing/#cookie-deprecation-value

We will *not* be using Client Hints to send the labels, but instead the current design relies on the presence of a specific cookie to opt-in to receiving the label in an HTTP header or calling a new JavaScript API.

We have also posted an initial Intent to Prototype to blink-dev: https://groups.google.com/a/chromium.org/g/blink-dev/c/8mlWTOcEzcA

**Comment by THATCHAPANTHATCHAPAN** [comment]
> Chrome is planning to use client hints to provide traffic labels for each of the testing modes. Do you have any concerns or feedback about using client hints for this purpose?
> 
> See https://developer.chrome.com/docs/privacy-sandbox/chrome-testing/ for context.

THATCHAPAN

**Comment by THATCHAPANTHATCHAPAN** [comment]
MACBOOKPRO
