### ISSUE TITLE
Questions regarding Chrome's new behavior

### ISSUE THREAD

**Issue by alucardmmc** [GoogleChromeLabs/privacy-sandbox-dev-support#139]
Hi! I'm currently trying to understand the changes a site would need to make to still work with this new update in a third party context.

The scenario I'm interested is:

- Site `a.com` renders in an iframe site `b.com`.
- `b.com` in this case has to use third party cookies for it to work.
- Currently if user blocks third party cookies:
  - `b.com` can't set any cookies.
  - `b.com` can't use local storage/session storage.

My questions are:

- With the third party cookie phaseout, will this behavior remain the same? Or is the local storage/session storage going to be accessible for `b.com`?
- Is there going to be a setting to still allow third party cookies? Currently we have the option `Allow all cookies` in Chrome settings. I'm also checking that Chrome Canary has the setting as `Allow third-party cookies`.
- Is there going to be a way for an user to allow an specific site to still use third party cookies? Currently we have the option `Sites that can always use cookies`. Chrome Canary has it as `Allowed to use third-party cookies`. Will this setting still be available after the update?
- What's the correct way to test the site with the changes Chrome will make to phase out third party cookie support? From what I've been checking you need to use Chrome Canary with these commands: `--test-third-party-cookie-phaseout --enable-features="FirstPartySets,StorageAccessAPI,StorageAccessAPIForOriginExtension,PageInfoCookiesSubpage,PrivacySandboxFirstPartySetsUI`. Am I correct with this?

**Comment by amedina** [comment]
Thank you for your great questions! Here are some related thoughts and answers.

> Question: With the third party cookie phaseout, will this behavior remain the same? Or is the local storage/session storage going to be accessible for [b.com](http://b.com/)?

Together with the phasing out of third-party cookies, other Storage APIs will also evolve to operate on a world where identity is partitioned at a first-party level. This means that Local Storage will also be partitioned. [This is a good article](https://developer.chrome.com/en/docs/privacy-sandbox/storage-partitioning/) to check to learn more about the topic.

> Question: Is there going to be a setting to still allow third party cookies? Currently we have the option Allow all cookies in Chrome settings. I'm also checking that Chrome Canary has the setting as Allow third-party cookies.

Third-party cookies will not be available in the same way that they are now. There will be mechanisms available (e.g. First-party Sets, CHIPS) which support scenarios that require some level of third-party context access, but in a privacy-preserving manner. 

> Question: Is there going to be a way for an user to allow an specific site to still use third party cookies? Currently we have the option Sites that can always use cookies. Chrome Canary has it as Allowed to use third-party cookies. Will this setting still be available after the update?

After third-party cookies are phased out, sites will not be able to access cookies as they do now in third-party contexts, except in cases supported by alternative mechanisms such as FPS or CHIPS.

> Question: What's the correct way to test the site with the changes Chrome will make to phase out third party cookie support? 

The approach you indicated is correct. Since Web Storage APIs will also be partitioned at first-party level, testing your site with the aforementioned flags will include such behaviors in the browser and if your site is using any of those AP relying on them being unpartitioned, they will not work. Also, if you want to test implementations using the new capabilities, the way you described is the way to go. [This is a good article](https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/#:~:text=In%20Chrome%20version%20115%20or,%2Dparty%2Dcookies%2Dphaseout%20.) to have as a reference. 

If you just want to test what happens if cookies are blocked, you can simply block third-party cookies in chrome://settings. [This is another good article](https://www.chromium.org/Home/chromium-privacy/privacy-sandbox/third-party-cookie-phaseout/) as a reference.

**Comment by dmdabbs** [comment]
FWIW, the "Intent to Ship" discussion and ramp up announcements for Partitioning Storage, Service Workers, and Communication APIs are here: [https://groups.google.com/a/chromium.org/g/blink-dev/c/24hK6DKJnqY/m/ChL2WWx5CgAJ](https://groups.google.com/a/chromium.org/g/blink-dev/c/24hK6DKJnqY/m/ChL2WWx5CgAJ)

**Comment by dcohenEG** [comment]
@amedina ah okay
>But in this version of Chrome the setting to allow cookies on some sites is still available, and works as intended.

So the "Allowed to use third-party cookies" setting is currently available in this version of chrome, to make testing easier, but I should expect that setting to be removed in a future version. Is that right?

I think you meant to reference [this reference article](https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/) (the link your provided goes to a github search in this repo)?

**Comment by amedina** [comment]
Oops; fixed the link. Thank you.

**Comment by amedina** [comment]
> Is there a way to verify that CHIPS is supported by the browser? I'm guessing I would need to check the Chrome version with navigator.userAgent >= 114

That would work to ensure availability. 

> Do we know the Chrome version where third party cookies deprecation will start? The roadmap says that 3pc deprecation will start from January for 1% of users, so I guess the release that will have that change would be Chrome 121?

I am not sure the exact version that will come with everything, but it should >= 121.

**Comment by rowan-m** [comment]
Closing as the issue looks resolved, but please re-open or raise a new issue if there's more to discuss!
