### ISSUE TITLE
Third Party Cookie Deprecation - What Google Chrome Version Will Release These Changes?

### ISSUE THREAD

**Issue by estrudels** [GoogleChromeLabs/privacy-sandbox-dev-support#181]
Hey Google Chrome Labs team,

I am curious if there is a Google Chrome Version which will have the Third Party Cookie Deprecation

GA of Google Chrome I currently have is `119.0.6045.106`

Canary of Google Chrome I currently have is `121.0.6113.0`

If I could be informed on what version the Third Party Cookie Deprecation will being for Google Chrome, I could perform my testing on our product

Thank you

**Comment by miketaylr** [comment]
Hi there - for now, you can test with the `--test-third-party-cookie-phaseout` commandline switch, or enabled the chrome://flags/#test-third-party-cookie-phaseout flag. These are in Chrome 118 and above, but testing with Canary is typically a good idea as it may have recent bug fixes or feature updates.

See https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/#test for more info.

**Comment by estrudels** [comment]
@miketaylr  Thank you for your quick feedback!

**Comment by IanSun** [comment]
Hi @miketaylr, I'm curious, when Chrome ramps up the third-party cookie restrictions to 100% of users in Q3 2024, what versions of users will be affected? Will it only affect users with versions greater than 119, or will it affect users of all versions?

If so, what solution should we provide for users below version 114 since neither CHIPS nor Storage Access API is supported in these versions.

**Comment by wanderview** [comment]
I don't think we have identified an exact version for further rollout, but it should not affect older versions prior to M120.
