### ISSUE TITLE
Google docs editor iframe

### ISSUE THREAD

**Issue by joaosaro** [GoogleChromeLabs/privacy-sandbox-dev-support#188]
Hi!

I was reading the documentation related to third-party cookie deprecation, and if I understood, the only solution for Google Docs iframe is the published version. However, it's possible to embed the editor until the third-party cookie deprecation. CHIPS approach would need to be necessary on Google's side, so it isn't currently a solution.

After the phasing out, is there a way to embed Google Docs editor?

Thanks in advance

**Comment by lghall** [comment]
Hello! The Google Docs editor can already be embedded in browsers that don't support 3p cookies. Feel free to test it out in Firefox and Safari. The user will be shown a button to grant storage access to the iframe. The same solution is rolling out in Chrome ahead of 3p cookie deprecation.

**Comment by joaosaro** [comment]
Hi Ighall 👋 

I was testing and sometime it shows a UI to require permissions from the user, but it only shows up once in a while. It's something under development? Is there any documentation to check how to embed correctly? From what I read, we should embed the publish version, but we want the editor.

Most of the time, I'm getting this UI from iframe: 

![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/19707842/cec97c2a-4798-4881-9229-64f11ee54a50)

**Comment by lghall** [comment]
Yes, the rollout for Chrome will be completed by the end of 2023.

**Comment by lghall** [comment]
Great point! I've added this issue to our internal tracking and I'll report back here if/when we're able to address it. 

As an interim solution, you could ask users of your application to allowlist 3p cookies for the necessary <embedder-embeddee> pair in their browser if they encounter this particular issue.

**Comment by tadamcz** [comment]
Thanks!

I understand it's a slightly tricky one, as you may not wish to request the permission for all embedded documents that have "anyone with the link can view" as soon as they are loaded. However, some sort of long-term solution would be great, because the current behaviour is puzzling to users: if you click on the sign in button in the iframe, the browser redirects the entire page to the Google document (where the user is already signed in). So the permission request _never_ appears.

I haven't thought about this very thoroughly, but one possible flow for documents with "anyone with the link can view" would be:

- when user clicks "sign in" within the iframe, request Storage Access permissions
    - if permission is refused, do the current behavior (redirect the entire page to the Google sign-in)
    - if permission is granted, check if the user is already signed in.
        - if yes, update the iframe contents as appropriate
        - otherwise, do the current behavior

**Comment by clementsimon** [comment]
Closing as there hasn't been any additional discussion on this thread in more than 6 weeks. Please re-open if there are any more questions or developments.

**Comment by lghall** [comment]
Hello! Circling back that we have now addressed the issue reported by tadamcz@ - If the user can View but not Edit the document without logging in, clicking "Sign in" will prompt for storage access and allow them to authenticate and edit the document if they have access. Thank you for the report!
