### ISSUE TITLE
Injecting trial token to top level frame

### ISSUE THREAD

**Issue by saubrecht** [GoogleChromeLabs/privacy-sandbox-dev-support#238]
I have a top-level site a.com and a third-party site b.com. I have a trial token for b.com with Third-party matching enabled. I used JavaScript loaded from a.com to inject that token into top-level frame in a.com ("document.createElement ... document.head.append(meta)"). In DevTools the top-level frame shows that the Tpcd trial token is enabled and valid.
Later on a.com creates a child frame and loads b.com into that frame. However cookies with b.com domain are still blocked. Is this scenario supposed to work? 
Or do I need add the trial token also to all response from b.com?

**Comment by saubrecht** [comment]
The script is part of a.com's index.html - and as I posted before the token does show as green in the DevTools window.
Or is that not enough an indicator?

**Comment by wanderview** [comment]
This might be a devtools issue.  I'm checking internally.

**Comment by wanderview** [comment]
Yes, there appears to be a known devtools bug where it might show a token as valid even when it fails the 3P script injection check.  See:

https://bugs.chromium.org/p/chromium/issues/detail?id=1324621

**Comment by saubrecht** [comment]
I tried injecting the token by downloading a script from the 3rd party domain like this:

<img width="1401" alt="Screenshot 2024-01-26 at 17 00 29" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/91059254/59918f4d-9804-4be9-a7ba-cf9111eba632">

The token shows as active:

<img width="754" alt="Screenshot 2024-01-26 at 16 57 37" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/91059254/58fee7ab-b671-4176-a95b-c600fccea0f5">

But third party cookies are still being blocked:

<img width="1592" alt="Screenshot 2024-01-26 at 16 58 45" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/91059254/b51cbf8f-3a70-49cf-a2c1-a229c9bcc5be">

I am testing in Chrome 122.0.6261.6 (Official Build) beta (x86_64) with feature flags:
chrome://flags#third-party-cookie-deprecation-trial -> enabled
chrome://flags/#tracking-protection-3pcd -> enabled
chrome://flags/#tpcd-metadata-grants -> disabled

I can provide a HAR file if more debug info is needed.

What am I doing wrong?

**Comment by samdutton** [comment]
Is this the script to add the token as used by siteb.com (i.e. the embedded, third-party site)? Is the origin shown here (https://oraclepdemos.com) the origin of that site (or is https://oraclepdemos.com actually the top-level site? If the token is actually registered for the top-level site, that's why DevTools won't complain if you're injecting it (from the console) on the top-level site.

(Apologies if my assumptions are wrong here!)

In your case, it sounds as if the token should be registered for siteb.com (without "Third-party matching" selected) and provided in a header, meta tag, or via JavaScript in the sitebe.com iframe document.

You might also want to look into the [deprecation trial for top-level sites](https://developers.google.com/privacy-sandbox/3pcd/temporary-exceptions/first-party-deprecation-trial).

**Comment by hoodjoshua** [comment]
Since the token matches subdomains, it being provided by a subdomain of oraclepdemos.com shouldn't be an issue. 

> I tried injecting the token by downloading a script from the 3rd party domain like this:
> 
> <img alt="Screenshot 2024-01-26 at 17 00 29" width="1401" src="https://private-user-images.githubusercontent.com/91059254/300038020-59918f4d-9804-4be9-a7ba-cf9111eba632.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDk2MzUsIm5iZiI6MTcwNzQwOTMzNSwicGF0aCI6Ii85MTA1OTI1NC8zMDAwMzgwMjAtNTk5MThmNGQtOTgwNC00YmU5LWE3YmEtY2Y5MTExZWJhNjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE2MjIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNGFmNDMxMGVjZDNjZjU5ZWE3ZDk1YTBmMmU0YTFjZGFlMTJhMWMzODgzM2U3ODJhMDNmZjE0ZWNlZTlhMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jUlkGhrwe5cS5uFowy4adWdtS_koNf8wffU91GZ2SSE">

Have you tried adding the script element directly to the document instead of appending it through the console? 

Also, have you tried this with a new Chrome profile (without any enterprise policies)? Maybe there are some settings in the current profile that conflict with the settings deprecation trial.

**Comment by miketaylr** [comment]
> Have you tried adding the script element directly to the document instead of appending it through the console?

To my knowledge, the script needs to be injected before the relevant frame is loaded. I would be very surprised if adding the token via the console after the page is loaded would have any effect.

**Comment by saubrecht** [comment]
The token actually works. I was testing it in an anonymous window and I was told that the token would never work there.
When I used a new browser profile I was able to see that 3rd party cookies are passed in and in another profile I saw that cookies are rejected if the token isn't present.

The only weird thing is that the token unlocks the cookie jar for other first party domains too. For example adding the token to index.html of a.top.com enables 3rd party cookies for thirdparty.com. But if I open b.top.com site which also makes requests to thirdparty.com the cookies are enabled even though there's no token in b.top.com's index.html. Sounds a bit like a bug to me. Or is this expected behavior?

**Comment by hoodjoshua** [comment]
This is expected behavior. 

The token enables the trial, granting third-party cookie access, for the token origin (and subdomains of it in this case) when embedded by any origin on the eTLD+1 the token was provided under. So, if a subdomain matching token is used to enable the trial for https://thirdparty.com on an https://a.top.com page, then it will be enabled for all subdomains of https://thirdparty.com on all subdomains of https://top.com.
