### ISSUE TITLE
navigator.cookieDeprecationLabel does not exist

### ISSUE THREAD

**Issue by Andrii-Pavlenko** [GoogleChromeLabs/privacy-sandbox-dev-support#254]
I'm using `ModHeader - Modify HTTP headers` chrome extension to update all my request headers. 
<img width="601" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/53989171/3e8633f5-0c48-431d-850c-4fb95276afa8">

I also turned on all features in the Chrome.
<img width="841" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/53989171/73455392-1082-4a8a-89b1-19d67a2957b2">

In [chrome-facilitated-testing](https://chrome-facilitated-testing.glitch.me/) page I have everything `DETECTED` and `ENABLED` except values after `navigator.cookieDeprecationLabel` executed. But I can see that may the value `treatment_1.2` appears.
<img width="786" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/53989171/0b8fb33d-4751-47c9-ac75-969d72936c3c">

On my webpage `navigator.cookieDeprecationLabel` does not exists
<img width="618" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/53989171/14536aa5-55c0-4dae-95b2-bd37c1b07f44">

Did I missed something?

**Comment by johnivdel** [comment]
Hi, could you share what OS you are testing this on?

I would note that ModHeader is not going to result in the JS API giving you the correct label, I'd recommend just picking the desired label from the #tpc-phase-out-facilitated-testing flag, and not setting the Sec-Cookie-Deprecation header yourself.

As for why the JS API is not present, could you verify that the webpage you are testing on is secure (e.g. uses HTTPs)? The test page does see the navigator API exposed, so that would be my first guess.

**Comment by samdutton** [comment]
What version of Chrome are you using? `navigator.cookieDeprecationLabel` is supported in 122 (i.e. Beta) and above, IIRC.

As John says, you should pick a value from `chrome://flags/#tpc-phase-out-facilitated-testing` rather than set a value in a request header: it's the Chrome client that sets the `Sec-Cookie-Deprecation` header value if `receive-cookie-deprecation` is set, depending on which experiment group arm it's in (or an empty string if it's not in an experiment group).

<img width="918" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/205226/558021c6-cf9e-4339-a1e6-f712484b44d9">

**Comment by Andrii-Pavlenko** [comment]
So I'm using MacOS and Chrome `Version 121.0.6167.160 (Official Build) (x86_64)`. After changing `#tpc-phase-out-facilitated-testing` from `Enabled` to `Enabled Control 1`, I get `fake_control_1.1`. So it seems to work now. Thank you very much!
<img width="827" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/53989171/23ee7ced-5388-45b3-89d7-4d2a99aad469">


But will this test be useful for regular users who don't know about these flags and don't have them configured on their side?

**Comment by samdutton** [comment]
> But will this test be useful for regular users who don't know about these flags and don't have them configured on their side?

The demo is intended for developers, and the labels are designed to support technical testing of the Privacy Sandbox relevance and measurement APIs across organizations.

In other words, the labels and the demos are not intended for use by regular users (though they're welcome to try them out!)
