### ISSUE TITLE
RWS and service

### ISSUE THREAD

**Issue by fcurtiItaliaonline** [GoogleChromeLabs/privacy-sandbox-dev-support#257]
We are trying to enable 3rd party cookie on related website using RWS.

The RWS setup is the following
(listed domains are fake in this issue, the real domains are already merged on main RWS and consumed by Chrome)

primary.com as primary
associated.com as associated
service.com as service

**Scenario**
1. primary.com, the top level domain, call via XHR a handler to service domain and send some informations
2. the handler on service domain writes a cookie on service domain which contains received information
3. associated.com call via XHR a handler to service domain, the handler try to read the cookie and send response to associated.com

XHR is compliant with CORS 3rd party constraint (Access-Control-Allow-Origin, Access-Control-Allow-Credentials,...)

In 3rd party deprecation scenario is normal that
step 2: does not write a cookie on service domain
step 3: does not read the cookie

I would expect, after RWS setup consumed by Chrome, that step 2 and 3 runs fine but this is not what I found.

I can give more detailed information and real domains in order to have a check on real environment.

**Comment by cfredric** [comment]
Can you please confirm that you are using `document.requestStorageAccess()` or `document.requestStorageAccessFor(origin)` on your sites, before issuing the XHR that is supposed to include the third-party cookie?

RWS does not passively re-enable 3P cookie access; it just reduces user friction for *active* requests for 3P cookies in certain contexts. Please see https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#implementation_examples or https://related-website-sets.glitch.me/ for some example usage of the `requestStorageAccess` and `requestStorageAccessFor` APIs.

**Comment by fcurtiItaliaonline** [comment]
Right question,
in this time we do not yet implement document.requestStorageAccessFor(origin) in the javascript injected on primary.com or associated.com

We tried to simulate this behaviour via console using snippet as described here
https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#top-level_sites_requesting_cookie_access_on_behalf_of_cross-origin_sites

The promise returned by 
navigator.permissions.query({name:'top-level-storage-access',requestedOrigin: 'https://www.iolam.it'}
is _prompt_
We would attend _granted_

Test is possible visiting top level domain [supereva.it ](https://www.supereva.it/) website which is in RWS with service www.iolam.it
run the snippet below

```
function checkCookie() {
	fetch('https://www.iolam.it/service/up', {
		method: 'POST',
		credentials: 'include'
	  })
	  .then((response) => response.json())
	  .then((json) => {
			console.log(json);
	  });
}
  
navigator.permissions.query({name:'top-level-storage-access',requestedOrigin: 'https://www.iolam.it'}).then(res => {	
  if (res.state === 'granted') {
    // Permission has already been granted
    // You can request storage access without any user gesture
    console.log("Permission has already been granted");
    rSAFor();
  } else if (res.state === 'prompt') {
    // Requesting storage access requires user gesture
    // For example, clicking a button
    console.log("Requesting storage access requires user gesture");
    const btn = document.createElement("button");
    btn.textContent = "Grant access";
    btn.addEventListener('click', () => {
      // Request storage access
      rSAFor();
    });
    document.body.appendChild(btn);
  }
});

function rSAFor() {
  if ('requestStorageAccessFor' in document) {
    document.requestStorageAccessFor('https://www.iolam.it').then(
      (res) => {
        checkCookie();
      },
      (err) => {
        // Handle errors
      }
    );
  }
}
```

**Comment by fcurtiItaliaonline** [comment]
I also take a look on glitch.me page demo
Also here...
the Promise return "prompt"
Having user gesture It returns ERROR

"[rws-member-1.glitch.me] requestStorageAccessFor('https://related-website-sets.glitch.me').then(res => {…}, err => {…}) → ERROR: DOMException: requestStorageAccessFor not allowed"

![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/156331898/06325ecf-0f9c-41d7-b849-97fc32f7b106)

**Comment by cfredric** [comment]
> The promise returned by
navigator.permissions.query({name:'top-level-storage-access',requestedOrigin: 'https://www.iolam.it'}/
is prompt
we expected to receive granted

This is expected behavior. RWS does not implicitly grant your sites permission to access their cookies; your sites must still use `requestStorageAccess` or `requestStorageAccessFor` to request access. (In Chrome, that request is automatically granted if the sites are in the same RWS.) So the permission status should be "prompt" until you actually request access.

I tried executing the code you provided, and it worked as expected for me: 
![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/4204485/16cc68c6-a64d-4496-9f41-e995c19b24a6)


(The network request did not include a cookie, but that's because I don't have any cookies for supereva.it. No cookies were blocked.)

> I take a look on glitch.me page demo
>
> Also here...
>
> the Promise return "prompt"
> Having user gesture It returns ERROR

I can't reproduce this failure. The demo works properly for me (in Chrome 123):
![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/4204485/264a785b-01fd-44e4-8294-4f9313e9435d)

When you test that demo, please be sure you follow the setup instructions on https://related-website-sets.glitch.me/. The RWS that the demo relies on is *not* in the [public RWS repository](https://github.com/GoogleChrome/related-website-sets) (since it doesn't need to be), so the demo will not work properly unless you follow the setup steps.

**Comment by fcurtiItaliaonline** [comment]
Supereva.it and www.iolam.it are already RWS members

![Related website sets membership](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/156331898/78d26392-1743-433e-a670-21098fa84897)

I still receiving prompt running the snippet below on Supereva.it console, granted is expected
![permission prompt](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/156331898/f74aa8ca-02ed-4e6e-aea9-2451b468596a)

Do you have an idea why your test returned "granted" and "prompt" for me?
I'm working on Ubuntu,
chrome version is
Version 122.0.6261.57 (Official Build) (64-bit)

another question,
how can we remove "granted status" if the grant is done by click the prompt ?

**Comment by cfredric** [comment]
> I still receiving prompt running the snippet below on Supereva.it console, granted is expected

If I understand correctly, this is because your site does not yet call `requestStorageAccessFor`. Since the site does not request access, the browser does not grant the permission.

Once your site calls `requestStorageAccessFor` using the correct origin (and with user activation), you should see the permission status as "granted", like I did after I ran your script and clicked the "Grant access" button.

> another question,
> how can we remove "granted status" if the grant is done by click the prompt ?

We're working on a better way to do this, but for now, you can reset this permission by restarting the browser (visit `chrome://restart`).

**Comment by cfredric** [comment]
> but i'm calling the requestStorageAccessFor via console on supereva.it homepage
so are you telling me that the snippet launched on console (visiting supereva.it) does not reproduce what happens calling requestStorageAccessFor on site?

I see - in that case, I'm not sure why you're seeing "prompt". That's what I did to test out your site, and I saw "granted". Maybe the origin you typed into `requestStorageAccessFor(...)` doesn't match the origin you typed into the `navigator.permissions.query` call?

>We are testing in a RWS membership: supereva.it is associated and iolam.it is a service
So we do not expect any user gesture because promise has to return "granted" based on the RWS behaviour

A user gesture is still required on the first visit/call, even if the sites are in the same RWS.

Note that a "user gesture" and a "user prompt" are different things. Chrome will not show a permission prompt to users if the sites are in the same RWS; but Chrome still requires that the user has interacted with the page.

> Done
but still return granted because in the session before i clicked the prompt to grant access.
I think restart is not enough in order to reset the grant done by user gesture.
If i rembember well the user gesture grant has a lifetime of 30 days.

RWS-related permission grants do have a lifetime of 30 days, but they are currently not persisted to disk, so they disappear when the browser restarts. (Non-RWS-related Storage Access permissions, from the user prompt, do not disappear after a restart since they are persisted to disk.)

**Comment by fcurtiItaliaonline** [comment]
> I see - in that case, I'm not sure why you're seeing "prompt". That's what I did to test out your site, and I saw "granted". Maybe the origin you typed into `requestStorageAccessFor(...)` doesn't match the origin you typed into the `navigator.permissions.query` call?

The origin is always the same (www.iolam.it)

I'm trying to figure out the RWS behavioral and this is what I experienced also considering your suggestions

**Sites RWS members**
even if the sites are RWS members, the first time the user visit the page the permission.query always return "prompt".
Only after the click on button "Grant access" the user will be always authorized (for 30 days).

Could you please confirm if I understood well?
In this case this behaviour is not compliant with your previous comment
> Chrome will not show a permission prompt to users if the sites are in the same RWS

**Sites not RWS members**
if the sites are not RWS members,  the first time the user visit the page the permission.query always return "prompt" and this sounds good.
After the click on button "Grant access" the response is error
`NotAllowedError: requestStorageAccessFor not allowed`
And this sounds good as well.

> RWS-related permission grants do have a lifetime of 30 days, but they are currently not persisted to disk, so they disappear when the browser restarts. (Non-RWS-related Storage Access permissions, from the user prompt, do not disappear after a restart since they are persisted to disk.)

After the click on button "Grant access" I'm always grant even after the Browser restart ( chrome://restart ).
I need to solve this because, otherwise, I'm not able to do test starting from "scratch"

**Comment by cfredric** [comment]
> even if the sites are RWS members, the first time the user visit the page the permission.query always return "prompt".
Only after the click on button "Grant access" the user will be always authorized (for 30 days).

Yup, this is the expected behavior.

> In this case this behaviour is not compliant with your previous comment
>
>> Chrome will not show a permission prompt to users if the sites are in the same RWS

I think there's a misunderstanding of what a permission prompt is. A permission prompt is a piece of *browser UI* that the browser shows in order to get a yes/no answer from the user. The "grant access" button shown after executing the script on your site is *not* a permission prompt; it's just a button on your site, that the user can click or not click.

To see what a permission prompt looks like, try running through the demo on https://rws-member-1.glitch.me/request-storage-access.html *without* setting up the test's RWS first (i.e. do not provide the `--use-related-website-set=...` command line switch). In Chrome, you should see a browser prompt that says "related-website-sets.glitch.me wants to use info they've saved about you".

> After the click on button "Grant access" I'm always grant even after the Browser restart ( chrome://restart ).
I need to solve this because, otherwise, I'm not able to do test starting from "scratch"

Hm, I can reproduce this with both `requestStorageAccess()` and `requestStorageAccessFor(origin)` within a RWS. This is a bug (and I think a relatively new one); I've filed https://issues.chromium.org/326466941 to track it.

Can you tell me what version of Chrome you're using?

**Comment by fcurtiItaliaonline** [comment]
> Can you tell me what version of Chrome you're using?

Ubuntu 22.04.4 LTS

![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/156331898/7ee230ad-32ad-4bdb-acdc-643d055be236)

**Comment by fcurtiItaliaonline** [comment]
> I think there's a misunderstanding of what a permission prompt is. A permission prompt is a piece of _browser UI_ that the browser shows in order to get a yes/no answer from the user. The "grant access" button shown after executing the script on your site is _not_ a permission prompt; it's just a button on your site, that the user can click or not click.

Never seen the "permission prompt" showed by Browser.
In my experience the click on button "grant access" is the only way to give authorization, in RWS context, to a domain to enable cross domain storage access.

But therefore, reflecting on this, if it is already the browser that manages the authorization prompt towards the user, what is the use of asking for authorization via a specific button as described in [RWS developer guide](https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#top-level_sites_requesting_cookie_access_on_behalf_of_cross-origin_sites) ?

`navigator.permissions.query({name:'top-level-storage-access',requestedOrigin: 'https://www.iolam.it'}).then(res => {	
  if (res.state === 'granted') {
  ...
  ...
  ...
  } else if (res.state === 'prompt') {
    // Requesting storage access requires user gesture
    // For example, clicking a button
    console.log("Requesting storage access requires user gesture");
    const btn = document.createElement("button");
    btn.textContent = "Grant access";
    btn.addEventListener('click', () => {
      // Request storage access
      rSAFor();
    });
    document.body.appendChild(btn);
  }
});`

If this were the case, would the Browser ask the user for authorization and then immediately be followed by the application's request for authorization?



> Thanks. This will be fixed in Chrome 124, but in the meantime, you should be able to fix it locally if you start Chrome using this command-line flag:
> 
> ```
> google-chrome --disable-features="ActiveContentSettingExpiry"
> ```
> 
> When using that flag, browser restarts should clear the setting correctly.

Sounds good, I will try

**Comment by cfredric** [comment]
> But therefore, reflecting on this, if it is already the browser that manages the authorization prompt towards the user, what is the use of asking for authorization via a specific button as described in [RWS developer guide](https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#top-level_sites_requesting_cookie_access_on_behalf_of_cross-origin_sites) ?

I'd point out that Chrome doesn't require you to show a *button*, specifically, it just requires the user to have clicked (or pressed a key, etc.) in your site somewhere. (The click/keypress is what we call the "user interaction".) The RWS integration guide just gives an example that uses a dedicated button, since that's an easy thing for users to interact with.

If, instead of creating a dedicated button for granting access, you piggybacked the `requestStorageAccessFor` call onto another button or keypress done by your users, that would be fine as far as the RWS implementation is concerned.

The reason that Chrome requires a user gesture (also called user interaction, or user activation) before granting permission is because *non-RWS* usage of the Storage Access API (namely `requestStorageAccess()`) also requires a user gesture (because of a [web platform design principle](https://www.w3.org/TR/design-principles/#require-user-activation)). We want to encourage web developers to design their sites so that they work in all browsers - even browsers that don't support RWS (and would therefore require a user gesture when using `requestStorageAccess()`).

**Comment by fcurtiItaliaonline** [comment]
At the end the RWS membership scenario is more clear for me. I reviewed the RWS implementation in case of "prompt" using other user activation (such as mousedown event) and It runs as expected.

Thank you Chris for all your support.
