### ISSUE TITLE
Origin trial token displays as wrong origin whereas subdomain matching is activated

### ISSUE THREAD

**Issue by fhoering** [GoogleChromeLabs/privacy-sandbox-dev-support#34]
We activated the OT token on `https://criteo.com` domain inside an iframe loaded on fledge.criteo.com here:
https://www.vertbaudet.fr/baskets-elastiquees-garcon-en-toile-kaki-dino.htm?ProductId=701030657&FiltreCouleur=6726&CodBouw=300001329&t=2

iframe src:
https://fledge.criteo.com/tagging/advertiser?partnerId=895&uid=2c1da35d-9840-4548-9a7c-3e6b4c98d1c0&requestId=1d22f249-9c85-4168-9e3a-6eeaa01594ef

However the token on https://criteo.com with subdomain matching activated is marked as invalid domain:
![token_criteo](https://user-images.githubusercontent.com/13346472/167644268-64021181-e850-4243-a8b6-d4def55fac33.PNG)

Subdomain matching is activated as described here: https://developer.chrome.com/blog/origin-trial-troubleshooting/#subdomain
Initial question here: https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/discussions/30#discussioncomment-2609334

**Comment by samdutton** [comment]
Hi Fabian — I think this is happening because the token in the iframe is registered as a third-party token, but it's actually used in a first-party context (i.e. the iframe).

I would be great if DevTools could make this clearer — I'll see if we can sort this out. Thanks for the heads-up!

For the other page, the (third-party) token is actually in a third party script embedded in the iframe, so it works. Hope that makes sense...

**Comment by fhoering** [comment]
OK. I will reopen this issue then (closed it and asked a question instead) 

We thought activating 3rd party context would activate both with one token because we also use this token in a 3rd party context upfront.

We have a this loaded as a script in top level context and we would like to check fledge availability before calling the iframe. 

```
<script src="https://sslwidget.criteo.com/event?a=895&v=5.10.0&p0=e%3Dexd%26ui_client%3Danonyme%26ci%3D%26site_type%3Dd%26ref%3Dhttps%253A%252F%252Fgithub.com&p1=e%3Dvp%26ui_newcust%3D0%26p%3D7010306576726%26si%3D%26ui_tcid%3D20225220551811305813676&p2=e%3Ddis&adce=1&bundle=67knXV8lMkJZcjd2OThrNldCUWkxUSUyRnZUa0FzanpldnR3WHAwTUZaSGw1MzNGWm1XZmt3UmxrOGQ3SXRyMUhpNzhMdkVjZXR6dHF2bndUV2F3Z211QTFrakVielA0MnRZMnhkTVVTaWRRRFlqQ3hFSHglMkZPJTJGbWlMNmVBeWh2eEpYV0lNQll5T0tuMFd4d0FUaGtpSUhaYkVyTHJwZyUzRCUzRA&tld=vertbaudet.fr&fu=https%3A%2F%2Fwww.vertbaudet.fr%2Fbaskets-elastiquees-garcon-en-toile-kaki-dino.htm%3FProductId%3D701030657%26FiltreCouleur%3D6726%26CodBouw%3D300001329%26t%3D2&dtycbr=14009"></script>
```

the script checks fledge availbility and loads the iframe
```
<html>
<body>
<!--StartFragment-->

onLoad(() => {
--
  | if ("joinAdInterestGroup" in navigator) {
  | dropIframe(url, "Criteo Fledge iframe");
  | }
  | });

<!--EndFragment-->
</body>
</html>
````

My understanding is in this case I need the 3rd party token in the top level header and a token (the same for now) inside the iframe.
Can you confirm ?

(Note the the current top level token is on criteo.net and not on criteo.com yet because it is used for measurement api, we probably will add one on criteo.com and one on criteo.net)

**Comment by samdutton** [comment]
Sorry for delay in responding — yes, multiple tokens might be the solution for you here: third-party token for embedded script, 'first-party' (i.e. 'normal') token for script running in an iframe.

Quick response from the DevTools team: bugs.chromium.org/p/chromium/issues/detail?id=1324621

Thanks again for bringing up this issue. 

> I would expect a 50% chance that a users in France using chrome beta would have the trial allowed. But I checked on some browsers. It was never active.

The unified trial was [ramped up to 50%](https://groups.google.com/u/3/a/chromium.org/g/topics-api-announce/c/DBIzd9Pc59Y), but [a bug was found with Topics](https://groups.google.com/u/3/a/chromium.org/g/topics-api-announce/c/P0hyAAmUD3o). The bug was fixed straight away, but Topics got removed from the trial. It'll take another week or so before the fixed version of Chrome Beta propagates — origin trial updates will be posted on the mailing list.

**Comment by samdutton** [comment]
FYI: more information about ramp-up and timings [here](https://groups.google.com/a/chromium.org/g/attribution-reporting-api-dev/c/Zqeq6UPP5wk/m/LJ-euyRtAgAJ).
