### ISSUE TITLE
Getting TrialNotAllowed for PrivacySandboxAdsAPIs and empty array

### ISSUE THREAD

**Issue by dimitarandonov** [GoogleChromeLabs/privacy-sandbox-dev-support#53]
![image](https://user-images.githubusercontent.com/95618093/187896422-45b40be0-9bbd-4498-81f0-1ac703124d95.png)

**Comment by samdutton** [comment]
TrialNotAllowed means a trial feature is not available for the current user. In this case, that's probably because you're not included in the percentage of users for whom the trial is enabled on the release channel you're using.

https://developer.chrome.com/docs/web-platform/origin-trial-troubleshooting/#devtools-status

It looks like you're using chrome://flags or command-line flags to enable the API.

By default, the epoch length is one week: the API will return an empty array until topics have been calculated over that time period.

You might want to take a look at topics-demo.glitch.me, which shows how to set flags to change the epoch length, e.g. to 15 seconds.

**Comment by samdutton** [comment]
> So how can I become one of these users?


The Privacy Sandbox Relevance and Measurement trial is currently available to 50% of users on Canary, Dev and Beta, and 1% of users on Chrome Stable, on pages that provide a valid trial token (though FLEDGE has [temporarily been ramped down](https://groups.google.com/u/2/a/chromium.org/g/fledge-api-announce/c/NrjuJq7mUps)). The trial will gradually be rolled out to higher percentages, as testing progresses. 

Whether or not a user is included in the experimental group for the origin trial is controlled by Chrome Variations (also known as Field Trials). This make it possible to compare browser metrics between the group for whom a feature is made available, and those for whom the feature is not available, in order to help check for bugs or unexpected side effects. Individual users do not have control over inclusion in the experimental group, since that could skew results.

If you want to make trial features available for an individual user, you can use flags as you have done. If you are testing at scale across multiple users by taking part in the origin trial, you will need to factor in the level of availability. We will continue to provide updates on availability on blink-dev and the API groups such as [topics-api-announce](https://groups.google.com/u/2/a/chromium.org/g/topics-api-announce).

**Comment by samdutton** [comment]
Closing as completed, but feel free to reopen.
