### ISSUE TITLE
Issues running the Aggregation Service on sample data

### ISSUE THREAD

**Issue by CGossec** [GoogleChromeLabs/privacy-sandbox-dev-support#78]
Hello Privacy Sandbox support team,
We have been trying to complete a full end-to-end test of the Attribution Reporting API, which includes using the Aggregation Service to combine aggregatable reports.
First though, we wanted to verify that the sample data provided in [the Aggregation Service repository](https://github.com/privacysandbox/aggregation-service) worked, and that we had a valid output.
It turned out that we couldn’t make it work, and had `DECRYPTION_ERROR` errors returned by the service.
Similarly, when trying with our own Criteo production data, we had one `DECRYPTION_ERROR`  associated with every report we tried to aggregate on.
This is hard to debug, given that we have no working example to base ourselves off of.
Finally, we were also told to expect a `PRIVACY_BUDGET_EXHAUSTED` error when trying to process the sample data from the repository, but no such thing happened when running our latest tests today.
We registered for the Aggregation Service onboarding using [criteo.com](http://criteo.com/), whereas our reports are sent to another domain. Is this potentially related?
Do you have any suggestions? Are these issues known/being looked into?
P.S.: Here is the aggregation service output of the failed sample data request
```
{
    "job_status": "FINISHED",
    "request_received_at": "2023-01-11T16:53:44.431277Z",
    "request_updated_at": "2023-01-11T16:51:53.478080Z",
    "job_request_id": "test_sample_data",
    "input_data_blob_prefix": "input/output_reports.avro",
    "input_data_bucket_name": <bucket_name>,
    "output_data_blob_prefix": "output/output_reports.avro",
    "output_data_bucket_name": <bucket_name>,
    "postback_url": "",
    "result_info": {
        "return_code": "SUCCESS",
        "return_message": "Aggregation job successfully processed",
        "error_summary": {
            "error_counts": [
                {
                    "category": "DECRYPTION_ERROR",
                    "count": 1
                },
                {
                    "category": "NUM_REPORTS_WITH_ERRORS",
                    "count": 1
                }
            ]
        },
        "finished_at": "2023-01-11T16:51:53.473846Z"
    },
    "job_parameters": {
        "debug_run": "true",
        "debug_privacy_epsilon": "1.0",
        "output_domain_bucket_name": <bucket_name>,
        "output_domain_blob_prefix": "domain/output_domain.avro",
        "attribution_report_to": "measurement-api.criteo.com"
    }
}
```

**Comment by hostirosti** [comment]
Hi @CGossec, 
thank you for raising this issue. The sample batch and domain we are providing in the repository can only be used with the local testing tool and are not compatible with the AWS based aggregation service.

A `DECRYPTION_ERROR` points to possible misconfiguration of the aggregation service. 
There are multiple situations that result in an `DECRYPTION_ERROR`:
1. The `key_id` the report was encrypted with is not available on the coordinator site - unlikely in your case if you generated aggregatable reports on Chrome browser.
1. The aggregation service does not have permission to access the private key to decrypt the aggregatable report. This happens if the roles used by the aggregation service don't have the right permissions or the aggregation service enclave image hash is not in the allow list of the coordinator. -- to avoid this, use our prebuilt AWS EC2 image and make sure to set the roles provided during our onboarding in your `<your_env>.auto.tfvars`.

Please feel free to reach out `aggregation-service-support<at>google.com` for further support.

Cheers,
Aggregation Service Team

**Comment by CGossec** [comment]
Indeed, I had an in-depth look at our onboarding message, and it turns out some values were incorrect.
It is my understanding that this means we need to start a new onboarding process.

While we are at it though, I was told the following (allegedly from someone over on your side):
 
> “The reporting origin they've onboarded with is https://criteo.com, but the attribution_report_to in the payload [cf first msg] is measurement-api.criteo.com”
 
And was lead to believe that this might cause issues too.
Because this is hearsay, I would like to confirm this with you: what should be the reporting origin of this new onboarding request?

**Comment by Santana0426** [comment]
sometime information just keeps getting pushed through to emails and multiple digits. is it because of the new google llc

**Comment by CGossec** [comment]
Hello @hostirosti

> What should be the reporting origin of this new onboarding request?

I have not yet received any email regarding this question. Do you have any updates?

**Comment by CGossec** [comment]
Hello,

After a new onboarding with proper coordinates, the problem was successfully resolved :)
As a wrap up comment, the issues were:
* Wrong onboarding coordinates on our side.
* Reporting origin in your onboarding *should* be your reporting endpoint (with https protocol)

Thank you for your assistance!
